services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATURA_API_KEY=
      - CHUTES_API_KEY=
      - AUTH_TOKEN=some_secret_auth_token
      - POSTGRES_DSN=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5


  worker:
    build: .
    command: celery -A app.celery:celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_DSN=postgresql+asyncpg://postgres:postgres@db:5432/postgres

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
