version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.tasks.celery_worker worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
