name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run services
        run: docker compose up -d

      - name: Run tests inside API container
        run: docker compose exec api pytest --disable-warnings -v

      - name: Shutdown services
        if: always()
        run: docker compose down
